export interface Medicine {
  _id: string; // Unique identifier for the medicine (optional, generated by backend)
  brandName: string; // Commercial name of the medicine
  genericName: string; // Scientific/generic name
  dosageForm: string; // Form of the medicine (e.g., Tablet, Capsule)
  strength: string; // Amount of active ingredient (e.g., 500 mg)
  currentStockLevel: number; // Current quantity in stock
  reorderThreshold: number; // Minimum stock level to trigger reorder
  reorderQuantity: number; // Quantity to order when restocking
  expiryDate: string; // Expiration date (ISO format, e.g., 2026-12-31)
  batchNumber: string; // Batch or lot number for tracking
  storageConditions: string; // Storage requirements (e.g., Store at 15-25°C)
  supplierInfo: string; // Supplier name and contact details
  storageLocation: string; // Physical location in facility (e.g., Pharmacy Shelf A)
  prescriptionStatus: string; // Prescription, OTC, or Controlled Substance
  pricePerUnit: number; // Cost per unit (e.g., 0.50)
  receivedDate: string; // Date stock was received (ISO format, e.g., 2025-07-08)
  status: 'active' | 'inactive' | 'discontinued' | 'out-of-stock'; // Current status of the medicine
  imageURL?: string; // URL to an image of the medicine (optional)
  notes?: string; // Additional notes or special instructions (optional)
}